/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Administrador;

import Menu.frmMenu_Administrador;
import java.io.File;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Comparator;
import java.util.Formatter;
import Metodos.user;
import java.io.FileInputStream;
import java.util.Properties;
import javax.swing.JOptionPane;
/**
 *
 * @author kevin
 */
public class ModTarjeta extends javax.swing.JFrame {

     String barra = File.separator;      //Separador de la maquina 
    String ruta = System.getProperty("user.dir")+barra+"src"+barra+"archivos"+barra+"usuarios"+barra;        //Ruta principal
    
    File contenedor = new File(ruta);       
    File[] registros = contenedor.listFiles();      //Encuentra los registros de usuarios

    public user O;
    public ArrayList<user> a = new ArrayList<user>();
    
     public void ordenarPorNumero(File[] str) {    // Ordena los usuarios comparandolos unos con otros
        Arrays.sort(str, new Comparator<File>() {
                public int compare(File o1, File o2) {
                    int n1 = Extraer(o1.getName());
                    int n2 = Extraer(o2.getName());
                    return n1 - n2;
                }

                private int Extraer(String name) { // Obtiene el nombre de los usuarios
                    int i = 0;
                    try {
                        int s = name.indexOf('r')+1;
                        int e = name.lastIndexOf('.');
                        String number = name.substring(s, e);
                        i = Integer.parseInt(number);
                    } catch(Exception e) {
                       i = 0; 
                    }
                    return i;
                }
            }
        );
    }
    
    public ModTarjeta() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        setResizable(false);
        this.getContentPane().setBackground(java.awt.Color.WHITE);
        
        ordenarPorNumero(registros); //ordena los usuarios mediante el metodo
        
        for(int i=0;i<registros.length;i++){
        
            File url = new File(ruta+registros[i].getName());
            try{
                FileInputStream fis = new FileInputStream(url);
                Properties mostrar = new Properties();
                mostrar.load(fis);               

                O = new user(mostrar.getProperty("Nombre"),        
                                    mostrar.getProperty("Tarjeta"),
                                    mostrar.getProperty("PIN"),
                                    Integer.parseInt(mostrar.getProperty("Limite")),
                                    Integer.parseInt(mostrar.getProperty("Saldo")),
                                    mostrar.getProperty("Tipo"));
                a.add(O);                                                               // obtiene los datos del constructor 

            }catch(Exception e){}
            
        }
           llenar(); 
    }
    
    public void llenar(){
        usuarios.removeAllItems();
        
        for(int i = 0; i<a.size(); i++){
            usuarios.addItem(a.get(i).Tarjeta);
        }
    }
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        usuarios = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        notarjeta = new javax.swing.JTextField();
        btncrear = new javax.swing.JButton();
        btncrear2 = new javax.swing.JButton();
        btncrear1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Modificar Tarjeta");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Numero Actual:");

        usuarios.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuariosActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Nuevo Numero:");

        notarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notarjetaActionPerformed(evt);
            }
        });

        btncrear.setBackground(new java.awt.Color(51, 51, 51));
        btncrear.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btncrear.setForeground(new java.awt.Color(255, 255, 255));
        btncrear.setText("Ingresar Datos");
        btncrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncrearActionPerformed(evt);
            }
        });

        btncrear2.setBackground(new java.awt.Color(51, 51, 51));
        btncrear2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btncrear2.setForeground(new java.awt.Color(255, 255, 255));
        btncrear2.setText("Regresar");
        btncrear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncrear2ActionPerformed(evt);
            }
        });

        btncrear1.setBackground(new java.awt.Color(255, 0, 0));
        btncrear1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btncrear1.setForeground(new java.awt.Color(51, 51, 51));
        btncrear1.setText("Eliminar Texto");
        btncrear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncrear1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setText("16 Digitos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(btncrear, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(btncrear2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usuarios, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(notarjeta)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btncrear1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addComponent(notarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncrear)
                    .addComponent(btncrear2))
                .addGap(18, 18, 18)
                .addComponent(btncrear1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void Crear(int i){
        String archivo = ("user")+(i+1)+".txt";
        File crea_ubicación = new File(ruta);
                
        try{    
            crea_ubicación.mkdirs();
            Formatter crear = new Formatter(ruta+archivo);
            crear.format("%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s",
                    "Nombre="+a.get(i).Nombre,
                    "Tarjeta="+notarjeta.getText().toUpperCase(),
                    "PIN="+a.get(i).Pin,
                    "Limite="+a.get(i).limite,
                    "Saldo="+a.get(i).saldo,
                    "Tipo="+a.get(i).tipo);
            crear.close();          
            
        }catch(Exception e){}    
        
        llenar();
    }

    private void usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuariosActionPerformed

    private void notarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notarjetaActionPerformed

    private void btncrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncrearActionPerformed
        // TODO add your handling code here:

       Boolean E = false;
        
        if(notarjeta.getText().length()<16 || notarjeta.getText().length()>16){
            JOptionPane.showMessageDialog(null, "Verificar el Numero de la Tarjeta", "Error", JOptionPane.ERROR_MESSAGE);
         
            E = true;
        }
        
        for(int i = 0; i<a.size();i++){
             if(a.get(i).Tarjeta.equals(notarjeta.getText().toUpperCase())){
                 JOptionPane.showMessageDialog(null, "El Numero de la Tarjeta ya Existe", "Error", JOptionPane.ERROR_MESSAGE);
                 E = true;
               
                 break;
             }
        }
        
        if(!E){
            Modificar();
            JOptionPane.showMessageDialog(null, "El numero de Tarjeta fue Cambiado con Exito", "Usuario", JOptionPane.INFORMATION_MESSAGE);
        }else{
            
        }

    }//GEN-LAST:event_btncrearActionPerformed

    private void btncrear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncrear2ActionPerformed
        // TODO add your handling code here:
        frmMenu_Administrador x = new frmMenu_Administrador();
        this.setVisible(false);
        x.setVisible(true); // Regresar al menu de administrador
    }//GEN-LAST:event_btncrear2ActionPerformed

    private void btncrear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncrear1ActionPerformed
        // TODO add your handling code here:
        notarjeta.setText("");
      
    }//GEN-LAST:event_btncrear1ActionPerformed

public void Modificar(){

        for(int i = 0; i<a.size();i++){
             if(usuarios.getSelectedItem().toString().equals(a.get(i).Tarjeta.toUpperCase())){
                 a.get(i).Tarjeta = notarjeta.getText().toUpperCase();
                 Crear(i);
                 break;
             }             
        }
        
        
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModTarjeta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncrear;
    private javax.swing.JButton btncrear1;
    private javax.swing.JButton btncrear2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField notarjeta;
    private javax.swing.JComboBox<String> usuarios;
    // End of variables declaration//GEN-END:variables
}
